name: CI/CD Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    ci-cd:
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: store_manager
            DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
            DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

        steps:
            - name: Cloner dépôt
              uses: actions/checkout@v3

            - name: Configurer Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.11'

            - name: Installer les dépendances via requirements.txt
              run: pip install -r requirements.txt

            - name: Linter tous les fichiers Python
              run: |
                  find . -name "*.py" -not -path "./__pycache__/*" -not -path "./.venv/*" | xargs pylint --exit-zero || true

            - name: Lancer les tests (skippables)
              run: |
                  PYTHONPATH=$PYTHONPATH:./src pytest -v

            - name: Préparer Docker pour le build
              uses: docker/setup-buildx-action@v3

            - name: Connexion à Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Lister les fichiers
              run: ls -R
                  
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./docker/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
